version: '3.8'
services:
  backend:
    build: ./netflix_agent_backend
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "5000:5000"

  frontend:
    build: ./netflix_agent_front
    ports:
      - "80:3000"
    depends_on:
      - backend  # ✅ This should be the service name, not a path
