version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
