# name: Deploy to EC2

# # on:
# #   push:
# #     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.7.0
#         with:
#           ssh-private-key: ${{ secrets.EC2_KEY }}

#       - name: Copy files to EC2
#         run: |
#           ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
#             cd ~
#             if [ ! -d "netflix-chat-bot" ]; then
#               git clone https://github.com/raulmss/netflix-chat-bot.git
#             fi
#             cd netflix-chat-bot
#             git pull origin main
      
#             echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
      
#             docker compose down --remove-orphans || true
#             docker compose up -d --build
#           EOF
