FROM python:3.12-slim

WORKDIR /app
COPY . /app

# Avoid caching unnecessary files
ENV PIP_NO_CACHE_DIR=1

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]